//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirgapArchitectConfig) DeepCopyInto(out *AirgapArchitectConfig) {
	*out = *in
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(RouteConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PullSecret != nil {
		in, out := &in.PullSecret, &out.PullSecret
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirgapArchitectConfig.
func (in *AirgapArchitectConfig) DeepCopy() *AirgapArchitectConfig {
	if in == nil {
		return nil
	}
	out := new(AirgapArchitectConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirgappedConfig) DeepCopyInto(out *AirgappedConfig) {
	*out = *in
	if in.RegistryCredentials != nil {
		in, out := &in.RegistryCredentials, &out.RegistryCredentials
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.RHTAS != nil {
		in, out := &in.RHTAS, &out.RHTAS
		*out = new(AirgappedRHTASConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirgappedConfig.
func (in *AirgappedConfig) DeepCopy() *AirgappedConfig {
	if in == nil {
		return nil
	}
	out := new(AirgappedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirgappedRHTASConfig) DeepCopyInto(out *AirgappedRHTASConfig) {
	*out = *in
	if in.TrustedRootKeys != nil {
		in, out := &in.TrustedRootKeys, &out.TrustedRootKeys
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirgappedRHTASConfig.
func (in *AirgappedRHTASConfig) DeepCopy() *AirgappedRHTASConfig {
	if in == nil {
		return nil
	}
	out := new(AirgappedRHTASConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactOutput) DeepCopyInto(out *ArtifactOutput) {
	*out = *in
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(BundleOutput)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactOutput.
func (in *ArtifactOutput) DeepCopy() *ArtifactOutput {
	if in == nil {
		return nil
	}
	out := new(ArtifactOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactStorageConfig) DeepCopyInto(out *ArtifactStorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactStorageConfig.
func (in *ArtifactStorageConfig) DeepCopy() *ArtifactStorageConfig {
	if in == nil {
		return nil
	}
	out := new(ArtifactStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleOutput) DeepCopyInto(out *BundleOutput) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Config)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleOutput.
func (in *BundleOutput) DeepCopy() *BundleOutput {
	if in == nil {
		return nil
	}
	out := new(BundleOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleSource) DeepCopyInto(out *BundleSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleSource.
func (in *BundleSource) DeepCopy() *BundleSource {
	if in == nil {
		return nil
	}
	out := new(BundleSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertIssuerReference) DeepCopyInto(out *CertIssuerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertIssuerReference.
func (in *CertIssuerReference) DeepCopy() *CertIssuerReference {
	if in == nil {
		return nil
	}
	out := new(CertIssuerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBootstrap) DeepCopyInto(out *ClusterBootstrap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBootstrap.
func (in *ClusterBootstrap) DeepCopy() *ClusterBootstrap {
	if in == nil {
		return nil
	}
	out := new(ClusterBootstrap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterBootstrap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBootstrapList) DeepCopyInto(out *ClusterBootstrapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterBootstrap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBootstrapList.
func (in *ClusterBootstrapList) DeepCopy() *ClusterBootstrapList {
	if in == nil {
		return nil
	}
	out := new(ClusterBootstrapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterBootstrapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBootstrapSpec) DeepCopyInto(out *ClusterBootstrapSpec) {
	*out = *in
	out.InstallConfig = in.InstallConfig
	out.PullSecret = in.PullSecret
	if in.TrustBundle != nil {
		in, out := &in.TrustBundle, &out.TrustBundle
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkConfig)
		**out = **in
	}
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(NodePoolConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Compute != nil {
		in, out := &in.Compute, &out.Compute
		*out = new(NodePoolConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PostInstall != nil {
		in, out := &in.PostInstall, &out.PostInstall
		*out = new(PostInstallConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBootstrapSpec.
func (in *ClusterBootstrapSpec) DeepCopy() *ClusterBootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterBootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBootstrapStatus) DeepCopyInto(out *ClusterBootstrapStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Kubeconfig != nil {
		in, out := &in.Kubeconfig, &out.Kubeconfig
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBootstrapStatus.
func (in *ClusterBootstrapStatus) DeepCopy() *ClusterBootstrapStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterBootstrapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionInfo) DeepCopyInto(out *CollectionInfo) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionInfo.
func (in *CollectionInfo) DeepCopy() *CollectionInfo {
	if in == nil {
		return nil
	}
	out := new(CollectionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionPipeline) DeepCopyInto(out *CollectionPipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionPipeline.
func (in *CollectionPipeline) DeepCopy() *CollectionPipeline {
	if in == nil {
		return nil
	}
	out := new(CollectionPipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CollectionPipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionPipelineList) DeepCopyInto(out *CollectionPipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CollectionPipeline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionPipelineList.
func (in *CollectionPipelineList) DeepCopy() *CollectionPipelineList {
	if in == nil {
		return nil
	}
	out := new(CollectionPipelineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CollectionPipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionPipelineSpec) DeepCopyInto(out *CollectionPipelineSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	if in.Signing != nil {
		in, out := &in.Signing, &out.Signing
		*out = new(CosignSigningConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionPipelineSpec.
func (in *CollectionPipelineSpec) DeepCopy() *CollectionPipelineSpec {
	if in == nil {
		return nil
	}
	out := new(CollectionPipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionPipelineStatus) DeepCopyInto(out *CollectionPipelineStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionPipelineStatus.
func (in *CollectionPipelineStatus) DeepCopy() *CollectionPipelineStatus {
	if in == nil {
		return nil
	}
	out := new(CollectionPipelineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
	if in.LastCheck != nil {
		in, out := &in.LastCheck, &out.LastCheck
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectedConfig) DeepCopyInto(out *ConnectedConfig) {
	*out = *in
	out.ArtifactStorage = in.ArtifactStorage
	if in.TriggerTypes != nil {
		in, out := &in.TriggerTypes, &out.TriggerTypes
		*out = make([]TriggerType, len(*in))
		copy(*out, *in)
	}
	if in.Operators != nil {
		in, out := &in.Operators, &out.Operators
		*out = new(OperatorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RHTAS != nil {
		in, out := &in.RHTAS, &out.RHTAS
		*out = new(RHTASInstallerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RHTPA != nil {
		in, out := &in.RHTPA, &out.RHTPA
		*out = new(RHTPAInstallerConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectedConfig.
func (in *ConnectedConfig) DeepCopy() *ConnectedConfig {
	if in == nil {
		return nil
	}
	out := new(ConnectedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CosignSigningConfig) DeepCopyInto(out *CosignSigningConfig) {
	*out = *in
	if in.KeySecretRef != nil {
		in, out := &in.KeySecretRef, &out.KeySecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Keyless != nil {
		in, out := &in.Keyless, &out.Keyless
		*out = new(KeylessSigningConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CosignSigningConfig.
func (in *CosignSigningConfig) DeepCopy() *CosignSigningConfig {
	if in == nil {
		return nil
	}
	out := new(CosignSigningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CosignVerificationConfig) DeepCopyInto(out *CosignVerificationConfig) {
	*out = *in
	if in.PublicKeySecretRef != nil {
		in, out := &in.PublicKeySecretRef, &out.PublicKeySecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.EnterpriseContractPolicy != nil {
		in, out := &in.EnterpriseContractPolicy, &out.EnterpriseContractPolicy
		*out = new(EnterpriseContractPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CosignVerificationConfig.
func (in *CosignVerificationConfig) DeepCopy() *CosignVerificationConfig {
	if in == nil {
		return nil
	}
	out := new(CosignVerificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisconnectedPlatform) DeepCopyInto(out *DisconnectedPlatform) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisconnectedPlatform.
func (in *DisconnectedPlatform) DeepCopy() *DisconnectedPlatform {
	if in == nil {
		return nil
	}
	out := new(DisconnectedPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisconnectedPlatform) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisconnectedPlatformList) DeepCopyInto(out *DisconnectedPlatformList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DisconnectedPlatform, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisconnectedPlatformList.
func (in *DisconnectedPlatformList) DeepCopy() *DisconnectedPlatformList {
	if in == nil {
		return nil
	}
	out := new(DisconnectedPlatformList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisconnectedPlatformList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisconnectedPlatformSpec) DeepCopyInto(out *DisconnectedPlatformSpec) {
	*out = *in
	if in.Connected != nil {
		in, out := &in.Connected, &out.Connected
		*out = new(ConnectedConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Airgapped != nil {
		in, out := &in.Airgapped, &out.Airgapped
		*out = new(AirgappedConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Architect != nil {
		in, out := &in.Architect, &out.Architect
		*out = new(AirgapArchitectConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GitOps != nil {
		in, out := &in.GitOps, &out.GitOps
		*out = new(GitOpsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisconnectedPlatformSpec.
func (in *DisconnectedPlatformSpec) DeepCopy() *DisconnectedPlatformSpec {
	if in == nil {
		return nil
	}
	out := new(DisconnectedPlatformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisconnectedPlatformStatus) DeepCopyInto(out *DisconnectedPlatformStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastCollection != nil {
		in, out := &in.LastCollection, &out.LastCollection
		*out = new(CollectionInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.CollectionHistory != nil {
		in, out := &in.CollectionHistory, &out.CollectionHistory
		*out = make([]CollectionInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastImport != nil {
		in, out := &in.LastImport, &out.LastImport
		*out = new(ImportInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.ImportHistory != nil {
		in, out := &in.ImportHistory, &out.ImportHistory
		*out = make([]ImportInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]ComponentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RHTASRootKeys != nil {
		in, out := &in.RHTASRootKeys, &out.RHTASRootKeys
		*out = new(RHTASRootKeysInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisconnectedPlatformStatus.
func (in *DisconnectedPlatformStatus) DeepCopy() *DisconnectedPlatformStatus {
	if in == nil {
		return nil
	}
	out := new(DisconnectedPlatformStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseContractPolicy) DeepCopyInto(out *EnterpriseContractPolicy) {
	*out = *in
	out.ConfigMapRef = in.ConfigMapRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseContractPolicy.
func (in *EnterpriseContractPolicy) DeepCopy() *EnterpriseContractPolicy {
	if in == nil {
		return nil
	}
	out := new(EnterpriseContractPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsConfig) DeepCopyInto(out *GitOpsConfig) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsConfig.
func (in *GitOpsConfig) DeepCopy() *GitOpsConfig {
	if in == nil {
		return nil
	}
	out := new(GitOpsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportInfo) DeepCopyInto(out *ImportInfo) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportInfo.
func (in *ImportInfo) DeepCopy() *ImportInfo {
	if in == nil {
		return nil
	}
	out := new(ImportInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeylessSigningConfig) DeepCopyInto(out *KeylessSigningConfig) {
	*out = *in
	if in.OIDCClientSecret != nil {
		in, out := &in.OIDCClientSecret, &out.OIDCClientSecret
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeylessSigningConfig.
func (in *KeylessSigningConfig) DeepCopy() *KeylessSigningConfig {
	if in == nil {
		return nil
	}
	out := new(KeylessSigningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedKeycloakConfig) DeepCopyInto(out *ManagedKeycloakConfig) {
	*out = *in
	if in.TLSSecret != nil {
		in, out := &in.TLSSecret, &out.TLSSecret
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.CertIssuer != nil {
		in, out := &in.CertIssuer, &out.CertIssuer
		*out = new(CertIssuerReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedKeycloakConfig.
func (in *ManagedKeycloakConfig) DeepCopy() *ManagedKeycloakConfig {
	if in == nil {
		return nil
	}
	out := new(ManagedKeycloakConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorImport) DeepCopyInto(out *MirrorImport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorImport.
func (in *MirrorImport) DeepCopy() *MirrorImport {
	if in == nil {
		return nil
	}
	out := new(MirrorImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MirrorImport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorImportList) DeepCopyInto(out *MirrorImportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MirrorImport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorImportList.
func (in *MirrorImportList) DeepCopy() *MirrorImportList {
	if in == nil {
		return nil
	}
	out := new(MirrorImportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MirrorImportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorImportSpec) DeepCopyInto(out *MirrorImportSpec) {
	*out = *in
	out.Bundle = in.Bundle
	out.TargetRegistry = in.TargetRegistry
	out.Publish = in.Publish
	if in.Verify != nil {
		in, out := &in.Verify, &out.Verify
		*out = new(CosignVerificationConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorImportSpec.
func (in *MirrorImportSpec) DeepCopy() *MirrorImportSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorImportStatus) DeepCopyInto(out *MirrorImportStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorImportStatus.
func (in *MirrorImportStatus) DeepCopy() *MirrorImportStatus {
	if in == nil {
		return nil
	}
	out := new(MirrorImportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorRelease) DeepCopyInto(out *MirrorRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorRelease.
func (in *MirrorRelease) DeepCopy() *MirrorRelease {
	if in == nil {
		return nil
	}
	out := new(MirrorRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MirrorRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorReleaseList) DeepCopyInto(out *MirrorReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MirrorRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorReleaseList.
func (in *MirrorReleaseList) DeepCopy() *MirrorReleaseList {
	if in == nil {
		return nil
	}
	out := new(MirrorReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MirrorReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorReleaseSpec) DeepCopyInto(out *MirrorReleaseSpec) {
	*out = *in
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(BundleOutput)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorReleaseSpec.
func (in *MirrorReleaseSpec) DeepCopy() *MirrorReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorReleaseStatus) DeepCopyInto(out *MirrorReleaseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorReleaseStatus.
func (in *MirrorReleaseStatus) DeepCopy() *MirrorReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(MirrorReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfig) DeepCopyInto(out *NetworkConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfig.
func (in *NetworkConfig) DeepCopy() *NetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolConfig) DeepCopyInto(out *NodePoolConfig) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(NodeResources)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolConfig.
func (in *NodePoolConfig) DeepCopy() *NodePoolConfig {
	if in == nil {
		return nil
	}
	out := new(NodePoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResources) DeepCopyInto(out *NodeResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResources.
func (in *NodeResources) DeepCopy() *NodeResources {
	if in == nil {
		return nil
	}
	out := new(NodeResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OLMSubscriptionConfig) DeepCopyInto(out *OLMSubscriptionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OLMSubscriptionConfig.
func (in *OLMSubscriptionConfig) DeepCopy() *OLMSubscriptionConfig {
	if in == nil {
		return nil
	}
	out := new(OLMSubscriptionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorConfig) DeepCopyInto(out *OperatorConfig) {
	*out = *in
	if in.OpenShiftPipelines != nil {
		in, out := &in.OpenShiftPipelines, &out.OpenShiftPipelines
		*out = new(OLMSubscriptionConfig)
		**out = **in
	}
	if in.Keycloak != nil {
		in, out := &in.Keycloak, &out.Keycloak
		*out = new(OLMSubscriptionConfig)
		**out = **in
	}
	if in.RHTAS != nil {
		in, out := &in.RHTAS, &out.RHTAS
		*out = new(OLMSubscriptionConfig)
		**out = **in
	}
	if in.RHTPA != nil {
		in, out := &in.RHTPA, &out.RHTPA
		*out = new(OLMSubscriptionConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorConfig.
func (in *OperatorConfig) DeepCopy() *OperatorConfig {
	if in == nil {
		return nil
	}
	out := new(OperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorInstall) DeepCopyInto(out *OperatorInstall) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorInstall.
func (in *OperatorInstall) DeepCopy() *OperatorInstall {
	if in == nil {
		return nil
	}
	out := new(OperatorInstall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostInstallConfig) DeepCopyInto(out *PostInstallConfig) {
	*out = *in
	if in.Operators != nil {
		in, out := &in.Operators, &out.Operators
		*out = make([]OperatorInstall, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostInstallConfig.
func (in *PostInstallConfig) DeepCopy() *PostInstallConfig {
	if in == nil {
		return nil
	}
	out := new(PostInstallConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublishConfig) DeepCopyInto(out *PublishConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublishConfig.
func (in *PublishConfig) DeepCopy() *PublishConfig {
	if in == nil {
		return nil
	}
	out := new(PublishConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHTASDatabaseConfig) DeepCopyInto(out *RHTASDatabaseConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHTASDatabaseConfig.
func (in *RHTASDatabaseConfig) DeepCopy() *RHTASDatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(RHTASDatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHTASInstallerConfig) DeepCopyInto(out *RHTASInstallerConfig) {
	*out = *in
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(RHTASOIDCConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(RHTASDatabaseConfig)
		**out = **in
	}
	if in.TrustedRootKeys != nil {
		in, out := &in.TrustedRootKeys, &out.TrustedRootKeys
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHTASInstallerConfig.
func (in *RHTASInstallerConfig) DeepCopy() *RHTASInstallerConfig {
	if in == nil {
		return nil
	}
	out := new(RHTASInstallerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHTASOIDCConfig) DeepCopyInto(out *RHTASOIDCConfig) {
	*out = *in
	if in.Managed != nil {
		in, out := &in.Managed, &out.Managed
		*out = new(ManagedKeycloakConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHTASOIDCConfig.
func (in *RHTASOIDCConfig) DeepCopy() *RHTASOIDCConfig {
	if in == nil {
		return nil
	}
	out := new(RHTASOIDCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHTASRootKeysInfo) DeepCopyInto(out *RHTASRootKeysInfo) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHTASRootKeysInfo.
func (in *RHTASRootKeysInfo) DeepCopy() *RHTASRootKeysInfo {
	if in == nil {
		return nil
	}
	out := new(RHTASRootKeysInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHTPADatabaseConfig) DeepCopyInto(out *RHTPADatabaseConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHTPADatabaseConfig.
func (in *RHTPADatabaseConfig) DeepCopy() *RHTPADatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(RHTPADatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHTPAInstallerConfig) DeepCopyInto(out *RHTPAInstallerConfig) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(RHTPAStorageConfig)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(RHTPADatabaseConfig)
		**out = **in
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(RHTPAOIDCConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHTPAInstallerConfig.
func (in *RHTPAInstallerConfig) DeepCopy() *RHTPAInstallerConfig {
	if in == nil {
		return nil
	}
	out := new(RHTPAInstallerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHTPAOIDCConfig) DeepCopyInto(out *RHTPAOIDCConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHTPAOIDCConfig.
func (in *RHTPAOIDCConfig) DeepCopy() *RHTPAOIDCConfig {
	if in == nil {
		return nil
	}
	out := new(RHTPAOIDCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHTPAStorageConfig) DeepCopyInto(out *RHTPAStorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHTPAStorageConfig.
func (in *RHTPAStorageConfig) DeepCopy() *RHTPAStorageConfig {
	if in == nil {
		return nil
	}
	out := new(RHTPAStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConfig) DeepCopyInto(out *RegistryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConfig.
func (in *RegistryConfig) DeepCopy() *RegistryConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteConfig) DeepCopyInto(out *RouteConfig) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteConfig.
func (in *RouteConfig) DeepCopy() *RouteConfig {
	if in == nil {
		return nil
	}
	out := new(RouteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Config) DeepCopyInto(out *S3Config) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Config.
func (in *S3Config) DeepCopy() *S3Config {
	if in == nil {
		return nil
	}
	out := new(S3Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}
