apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: mirror-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/mathianasj/mirror-operator-catalog:v0.0.1
  displayName: Mirror Operator (Dev)
  publisher: mathianasj
  updateStrategy:
    registryPoll:
      interval: 10m
