apiVersion: mirror.mirror.mathianasj.github.com/v1
kind: CollectionPipeline
metadata:
  labels:
    app.kubernetes.io/name: mirror-operator
    app.kubernetes.io/managed-by: kustomize
  name: collection-v4-17-incremental
spec:
  imageSetConfig: |
    kind: ImageSetConfiguration
    apiVersion: mirror.openshift.io/v1alpha2
    storageConfig:
      local:
        path: /workspace/output
    mirror:
      platform:
        channels:
          - name: stable-4.17
            type: ocp
  triggerType: manual
  incremental: true
  baseVersion: v2026.05.26.001-manual
  signing:
    keySecretRef:
      name: cosign-signing-key
    passwordSecretRef:
      name: cosign-signing-key
  storage:
    output:
      pvc: mirror-bundles
      filename: release-v4.17.tar
