apiVersion: mirror.mirror.mathianasj.github.com/v1
kind: DisconnectedPlatform
metadata:
  labels:
    app.kubernetes.io/name: mirror-operator
    app.kubernetes.io/managed-by: kustomize
  name: disconnected-platform-clusterissuer
spec:
  mode: connected
  connected:
    collectionSchedule: "0 2 * * 0"
    mirrorRegistry: "quay.example.com/mirror"
    artifactStorage:
      size: 2Ti
    triggerTypes:
      - scheduled
      - manual
    operators:
      openshiftPipelines: {}
      keycloak: {}
      rhtas: {}
      rhtpa: {}
    rhtas:
      oidc:
        managed:
          enabled: true
          realm: "trusted-artifact-signer"
          # Use existing ClusterIssuer (e.g., Let's Encrypt)
          certIssuer:
            name: letsencrypt-prod
            kind: ClusterIssuer
        type: "email"
      database:
        host: "postgres.example.com"
        name: "rhtas"
        port: 5432
    rhtpa:
      storage:
        type: local
        size: 20Gi
      database:
        host: postgres.example.com
        name: rhtpa
        username: rhtpa
        password: change-me
  architect:
    enabled: true
